name: Build
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run Jest
        run: npm test
